import {
  User,
  Workspace,
  ClientAccount,
  Website,
  AuditRun,
  AuditIssue,
  Task,
  KeywordItem,
  ContentItem,
  CompetitorSnapshot,
  BusinessProfile,
  LeadItem,
  ReportItem,
  IntegrationStatus,
  WorkerActivity,
  AIMessage,
} from './types';

export const INITIAL_USER: User = {
  id: 'user-arthur',
  name: 'Arthur Vance',
  email: 'arthurscreatives@gmail.com',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  role: 'Owner',
};

export const INITIAL_WORKSPACES: Workspace[] = [
  {
    id: 'ws-arthurs',
    name: 'Arthur’s Creatives (Agency)',
    type: 'agency',
    ownerId: 'user-arthur',
    plan: 'Agency Pro',
    creditsRemaining: 840,
    totalCredits: 1000,
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'ws-solas',
    name: 'Solas Health & Wellness',
    type: 'business',
    ownerId: 'user-arthur',
    plan: 'Growth',
    creditsRemaining: 320,
    totalCredits: 500,
    createdAt: '2026-02-01T11:30:00Z',
  },
];

export const INITIAL_CLIENTS: ClientAccount[] = [
  {
    id: 'client-solas',
    workspaceId: 'ws-arthurs',
    name: 'Solas Health & Wellness',
    contactName: 'Dr. Elena Rostova',
    contactEmail: 'elena@solashealthwellness.com',
    websiteCount: 1,
    activeTier: 'Growth Monthly ($1,500/mo)',
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'client-apex',
    workspaceId: 'ws-arthurs',
    name: 'Apex Legal Partners',
    contactName: 'Marcus Vance',
    contactEmail: 'marcus@apexlegalpartners.com',
    websiteCount: 1,
    activeTier: 'Enterprise Retainer ($3,200/mo)',
    createdAt: '2026-02-14T14:20:00Z',
  },
];

export const INITIAL_WEBSITES: Website[] = [
  {
    id: 'site-arthurs',
    workspaceId: 'ws-arthurs',
    domain: 'arthurscreatives.com',
    name: 'Arthur’s Creatives Main',
    businessType: 'AI Marketing & SEO Agency',
    targetLocation: 'Austin, Texas & Nationwide',
    createdAt: '2026-01-16T10:00:00Z',
    lastAuditDate: '2026-09-08T15:30:00Z',
    auditScore: 84,
    connectedGSC: true,
    connectedGA4: true,
    crawlSettings: {
      maxPages: 50,
      crawlSubdomains: false,
      excludedPaths: ['/admin', '/private'],
      crawlFrequency: 'Weekly',
    },
  },
  {
    id: 'site-solas',
    workspaceId: 'ws-arthurs',
    clientId: 'client-solas',
    domain: 'solashealthwellness.com',
    name: 'Solas Health Clinic',
    businessType: 'Integrative Medicine & Longevity Clinic',
    targetLocation: 'Austin, TX',
    createdAt: '2026-02-02T12:00:00Z',
    lastAuditDate: '2026-09-05T09:15:00Z',
    auditScore: 78,
    connectedGSC: true,
    connectedGA4: false,
    crawlSettings: {
      maxPages: 30,
      crawlSubdomains: false,
      excludedPaths: ['/portal'],
      crawlFrequency: 'Bi-weekly',
    },
  },
];

export const INITIAL_AUDIT_RUNS: AuditRun[] = [
  {
    id: 'audit-run-001',
    websiteId: 'site-arthurs',
    url: 'https://arthurscreatives.com',
    startedAt: '2026-09-08T15:28:10Z',
    completedAt: '2026-09-08T15:30:42Z',
    status: 'completed',
    score: 84,
    pagesScanned: 24,
    criticalCount: 1,
    highCount: 2,
    mediumCount: 3,
    lowCount: 2,
    passedChecksCount: 48,
    crawlScope: {
      maxPages: 50,
      subdomains: false,
    },
    metrics: {
      avgResponseTimeMs: 340,
      brokenLinks: 1,
      missingTitles: 0,
      missingDescriptions: 2,
      missingH1: 0,
      missingAltText: 4,
      noIndexPages: 1,
      schemaDetectedPages: 18,
    },
  },
];

export const INITIAL_ISSUES: AuditIssue[] = [
  {
    id: 'issue-001',
    runId: 'audit-run-001',
    websiteId: 'site-arthurs',
    title: 'Missing Canonical Tag on Primary Services Page',
    severity: 'critical',
    category: 'Crawlability',
    affectedUrl: 'https://arthurscreatives.com/services/ai-seo-growth',
    observedEvidence: 'HTML response inspected: <head> does not contain <link rel="canonical" href="..."> element.',
    detectedAt: '2026-09-08T15:29:10Z',
    explanation: 'Without a self-referencing canonical tag, search engines may split ranking authority across trailing slashes, URL parameters, or duplicate protocol variants.',
    recommendedFix: 'Insert `<link rel="canonical" href="https://arthurscreatives.com/services/ai-seo-growth" />` inside the document head.',
    verificationMethod: 'Crawl the page URL and inspect document head for matching canonical URL.',
    taskStatus: 'created',
    taskId: 'task-001',
    isHumanJudgmentNeeded: false,
  },
  {
    id: 'issue-002',
    runId: 'audit-run-001',
    websiteId: 'site-arthurs',
    title: 'Missing Meta Description on 2 High-Intent Service Pages',
    severity: 'high',
    category: 'On-Page SEO',
    affectedUrl: 'https://arthurscreatives.com/services/digital-workforce',
    observedEvidence: '<meta name="description"> tag is completely absent in rendered HTML.',
    detectedAt: '2026-09-08T15:29:32Z',
    explanation: 'Pages without meta descriptions force search engines to extract random snippets from body copy, reducing click-through rates (CTR) in search results.',
    recommendedFix: 'Author a compelling 150-160 character meta description emphasizing AI agents and business automation value proposition.',
    verificationMethod: 'Validate meta name="description" tag exists with length between 120 and 160 characters.',
    taskStatus: 'created',
    taskId: 'task-002',
    isHumanJudgmentNeeded: true,
  },
  {
    id: 'issue-003',
    runId: 'audit-run-001',
    websiteId: 'site-arthurs',
    title: 'Broken Internal Anchor Link in Footer Navigation',
    severity: 'high',
    category: 'Links',
    affectedUrl: 'https://arthurscreatives.com/resources/2025-ai-guide',
    observedEvidence: 'Footer link href="/resources/2025-ai-guide" returned HTTP status 404 (Not Found).',
    detectedAt: '2026-09-08T15:29:45Z',
    explanation: 'Internal broken links waste crawl budget and cause immediate bounce friction for potential clients looking for guides.',
    recommendedFix: 'Update the footer link href to point to the active URL `/resources/2026-ai-playbook` or set up a 301 permanent redirect.',
    verificationMethod: 'Check HTTP status code of destination URL; must return 200 OK.',
    taskStatus: 'unassigned',
    isHumanJudgmentNeeded: false,
  },
  {
    id: 'issue-004',
    runId: 'audit-run-001',
    websiteId: 'site-arthurs',
    title: 'Multiple H1 Tags Detected on Case Studies Overview',
    severity: 'medium',
    category: 'Headings & Content',
    affectedUrl: 'https://arthurscreatives.com/case-studies',
    observedEvidence: 'Found 3 distinct <h1> elements: "Our Work", "Client Success Stories", and "Recent Breakthroughs".',
    detectedAt: '2026-09-08T15:30:02Z',
    explanation: 'While HTML5 permits multiple H1s, best practice is a single primary H1 defining page topic to avoid confusing topic clarity for search crawlers.',
    recommendedFix: 'Keep "Client Case Studies & Growth Breakthroughs" as the sole H1, and demote secondary section headings to H2.',
    verificationMethod: 'Count <h1> elements on page; exactly one should exist.',
    taskStatus: 'unassigned',
    isHumanJudgmentNeeded: true,
  },
  {
    id: 'issue-005',
    runId: 'audit-run-001',
    websiteId: 'site-arthurs',
    title: 'Hero Images Missing Alt Attributes on 4 Service Pages',
    severity: 'medium',
    category: 'On-Page SEO',
    affectedUrl: 'https://arthurscreatives.com/services/automation',
    observedEvidence: '<img src="/assets/hero-agents.png"> element lacks an `alt` attribute.',
    detectedAt: '2026-09-08T15:30:15Z',
    explanation: 'Missing alt tags degrade accessibility for screen readers and miss image search indexing opportunities.',
    recommendedFix: 'Add descriptive alt text such as "Interactive diagram of Arthur’s AI agent ecosystem automating business workflows".',
    verificationMethod: 'Ensure all <img> elements have non-empty alt attributes.',
    taskStatus: 'unassigned',
    isHumanJudgmentNeeded: true,
  },
  {
    id: 'issue-006',
    runId: 'audit-run-001',
    websiteId: 'site-arthurs',
    title: 'Missing Organization Schema.org Structured Data on Homepage',
    severity: 'low',
    category: 'Structured Data',
    affectedUrl: 'https://arthurscreatives.com',
    observedEvidence: 'No <script type="application/ld+json"> with schema type "Organization" or "LocalBusiness" located.',
    detectedAt: '2026-09-08T15:30:25Z',
    explanation: 'Structured data clarifies entity knowledge, logos, social profiles, and contact points for Google Knowledge Graph.',
    recommendedFix: 'Implement JSON-LD script for Organization with name, url, logo, sameAs social links, and founder info.',
    verificationMethod: 'Check page head for valid JSON-LD containing schema.org/Organization.',
    taskStatus: 'unassigned',
    isHumanJudgmentNeeded: false,
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-001',
    workspaceId: 'ws-arthurs',
    websiteId: 'site-arthurs',
    issueId: 'issue-001',
    title: 'Inject Self-Referencing Canonical on /services/ai-seo-growth',
    description: 'Add `<link rel="canonical" href="https://arthurscreatives.com/services/ai-seo-growth" />` into the Next.js head component or layout metadata.',
    affectedUrl: 'https://arthurscreatives.com/services/ai-seo-growth',
    priority: 'Critical',
    category: 'Crawlability',
    owner: 'Arthur Vance',
    dueDate: '2026-09-12',
    status: 'In Progress',
    supportingEvidence: 'Audit Run #001 verified canonical tag is absent.',
    suggestedFix: 'Update layout.tsx metadata alternates: { canonical: "/services/ai-seo-growth" }',
    createdAt: '2026-09-08T16:00:00Z',
    updatedAt: '2026-09-09T10:00:00Z',
  },
  {
    id: 'task-002',
    workspaceId: 'ws-arthurs',
    websiteId: 'site-arthurs',
    issueId: 'issue-002',
    title: 'Write High-CTR Meta Description for Digital Workforce Page',
    description: 'Draft and deploy a 155-character meta description with compelling call to action.',
    affectedUrl: 'https://arthurscreatives.com/services/digital-workforce',
    priority: 'High',
    category: 'On-Page SEO',
    owner: 'Arthur Vance',
    dueDate: '2026-09-14',
    status: 'Open',
    supportingEvidence: 'Search snippet currently extracts raw cookie banner text.',
    suggestedFix: 'Deploy: "Build, train, and deploy intelligent AI agents for customer service, appointments, and sales. Explore Arthur’s AI Workforce today."',
    createdAt: '2026-09-08T16:15:00Z',
    updatedAt: '2026-09-08T16:15:00Z',
  },
  {
    id: 'task-003',
    workspaceId: 'ws-arthurs',
    websiteId: 'site-arthurs',
    title: 'Publish New Content Brief: "Local SEO with AI Agents"',
    description: 'Complete review of drafted guide targeting "local seo ai tools" and approve for publication.',
    affectedUrl: 'https://arthurscreatives.com/blog/local-seo-ai-tools',
    priority: 'Medium',
    category: 'Content',
    owner: 'Arthur Vance',
    dueDate: '2026-09-18',
    status: 'Awaiting Review',
    supportingEvidence: 'Keyword opportunity identified with 880 monthly search volume and low competition.',
    suggestedFix: 'Review factual statements regarding Google Business Profile guidelines before approving.',
    createdAt: '2026-09-06T11:00:00Z',
    updatedAt: '2026-09-09T14:30:00Z',
  },
  {
    id: 'task-004',
    workspaceId: 'ws-arthurs',
    websiteId: 'site-arthurs',
    title: 'Fix 301 Redirect for Legacy Whitepaper URL',
    description: 'Configure redirect in next.config.ts from /resources/2025-ai-guide to /resources/2026-ai-playbook.',
    affectedUrl: 'https://arthurscreatives.com/resources/2025-ai-guide',
    priority: 'High',
    category: 'Links',
    owner: 'Dev Team',
    dueDate: '2026-09-10',
    status: 'Completed',
    supportingEvidence: 'Audit detected 404 on footer click.',
    suggestedFix: 'Redirect rule active; verified with 301 response.',
    completionNotes: 'Added redirect rule to next.config.ts and re-verified HTTP response status 301 -> 200.',
    createdAt: '2026-09-08T17:00:00Z',
    updatedAt: '2026-09-10T11:00:00Z',
  },
];

export const INITIAL_KEYWORDS: KeywordItem[] = [
  {
    id: 'kw-001',
    workspaceId: 'ws-arthurs',
    websiteId: 'site-arthurs',
    keyword: 'ai seo platform for agencies',
    intent: 'Commercial',
    location: 'United States',
    searchVolume: 1600,
    difficulty: 38,
    cpc: 4.85,
    trend: '+24% YoY',
    targetPage: 'https://arthurscreatives.com/services/ai-seo-growth',
    cluster: 'AI SEO Tools & Platforms',
    sourceProvider: 'DataForSEO',
    measuredDate: '2026-09-01',
    tags: ['Core Service', 'High Intent'],
  },
  {
    id: 'kw-002',
    workspaceId: 'ws-arthurs',
    websiteId: 'site-arthurs',
    keyword: 'ai digital workforce for business',
    intent: 'Informational',
    location: 'United States',
    searchVolume: 2400,
    difficulty: 32,
    cpc: 3.10,
    trend: '+85% YoY',
    targetPage: 'https://arthurscreatives.com/services/digital-workforce',
    cluster: 'AI Agents & Automation',
    sourceProvider: 'DataForSEO',
    measuredDate: '2026-09-01',
    tags: ['Brand Pillar', 'Top of Funnel'],
  },
  {
    id: 'kw-003',
    workspaceId: 'ws-arthurs',
    websiteId: 'site-arthurs',
    keyword: 'local seo audit checklist 2026',
    intent: 'Informational',
    location: 'United States',
    searchVolume: 1200,
    difficulty: 26,
    cpc: 2.40,
    trend: '+15% YoY',
    targetPage: 'https://arthurscreatives.com/resources/local-seo-checklist',
    cluster: 'Local SEO Resources',
    sourceProvider: 'DataForSEO',
    measuredDate: '2026-09-01',
    tags: ['Lead Magnet', 'Resource'],
  },
  {
    id: 'kw-004',
    workspaceId: 'ws-arthurs',
    websiteId: 'site-arthurs',
    keyword: 'ai phone receptionist for clinics',
    intent: 'Transactional',
    location: 'United States',
    searchVolume: 880,
    difficulty: 29,
    cpc: 6.20,
    trend: '+40% YoY',
    targetPage: 'https://arthurscreatives.com/solutions/healthcare-agents',
    cluster: 'Vertical AI Agents',
    sourceProvider: 'DataForSEO',
    measuredDate: '2026-09-01',
    tags: ['Healthcare', 'High Value'],
  },
  {
    id: 'kw-005',
    workspaceId: 'ws-arthurs',
    websiteId: 'site-arthurs',
    keyword: 'how to fix missing canonical tags',
    intent: 'Informational',
    location: 'United States',
    searchVolume: 720,
    difficulty: 21,
    cpc: 1.80,
    trend: 'Stable',
    targetPage: undefined,
    cluster: 'Technical SEO Education',
    sourceProvider: 'AI Suggestion',
    measuredDate: '2026-09-05',
    tags: ['AI Suggested', 'Pending Validation'],
  },
];

export const INITIAL_CONTENT: ContentItem[] = [
  {
    id: 'cnt-001',
    workspaceId: 'ws-arthurs',
    websiteId: 'site-arthurs',
    title: 'The 2026 Guide to AI-Powered SEO Audits for Growing Agencies',
    contentType: 'Blog Article',
    targetKeyword: 'ai seo platform for agencies',
    status: 'Review',
    targetUrl: 'https://arthurscreatives.com/blog/ai-seo-audit-guide-2026',
    assignedAuthor: 'Arthur Vance',
    assignedReviewer: 'Elena Rostova',
    targetAudience: 'Digital agency owners, SEO directors, in-house marketing leads',
    brandVoice: 'Authoritative, clear, pragmatic, forward-looking',
    brief: {
      objective: 'Demonstrate how combining technical crawl data with conversational AI (LOVE Brain) cuts audit turnaround from 6 hours to 20 minutes.',
      suggestedHeadings: [
        'Why Traditional SEO Audits Overwhelm Clients',
        'Separating Observed Technical Facts from Hypotheses',
        'The Role of Specialized AI Workers in Technical Analysis',
        'From Audit Finding to Prioritized Task in One Click',
        'Agency Client Management & White-Label Reporting',
      ],
      suggestedWordCount: 1800,
      keyPoints: [
        'Highlight Arthur’s Creatives experience managing digital workforces.',
        'Emphasize evidence-backed fixes rather than vague SEO penalties.',
        'Detail verification workflows to prevent premature task closure.',
      ],
      internalLinkIdeas: [
        '/services/ai-seo-growth (anchor: AI SEO platform)',
        '/services/digital-workforce (anchor: autonomous AI workers)',
      ],
    },
    draftContent: `# The 2026 Guide to AI-Powered SEO Audits for Growing Agencies

Modern businesses don’t lack SEO data—they drown in it. An agency client handed a 90-page spreadsheet listing 4,000 "issues" is not empowered; they are paralyzed. 

At **Arthur’s Creatives**, our mandate with **AI SEO Love** is turning raw crawl telemetry into clear, prioritized business execution.

## 1. Why Traditional SEO Audits Overwhelm Clients
Most legacy crawlers treat a missing H1 on a terms-of-service page with the same panicked red badge as a broken canonical tag bleeding link equity. 

When presenting findings to stakeholders:
- **Observed facts** must be isolated from hypotheses. If a page lacks a meta description, that is an observed fact. That adding one *will* double organic clicks is an educated hypothesis.
- **Effort vs. impact scoring** must determine what gets fixed first.

## 2. From Audit Findings to Actionable Tasks
A diagnostic without an execution path is merely an invoice. Every critical finding—such as canonical mismatches or redirect loops—should convert instantly into an assigned ticket with exact source code snippets.`,
    optimizationNotes: [
      'Keyword density: "ai seo platform for agencies" appears 3 times naturally.',
      'Heading structure follows strict H1 -> H2 -> H3 hierarchy.',
      'Includes clear call-to-action to run a live website audit.',
    ],
    factualReviewNotes: [
      'FLAG FOR CONFIRMATION: Verify the stat "cuts audit turnaround from 6 hours to 20 minutes" with client team before final publish.',
      'CONFIRMED: Google Search Console API data connection rules are accurately cited.',
    ],
    versionHistory: [
      {
        version: 1,
        updatedAt: '2026-09-07T14:00:00Z',
        updatedBy: 'Arthur Vance',
        summary: 'Initial outline and brief generated by Content Worker.',
      },
      {
        version: 2,
        updatedAt: '2026-09-08T10:15:00Z',
        updatedBy: 'Arthur Vance',
        summary: 'Draft expanded to 1,200 words with factual review notes flagged.',
      },
    ],
    createdAt: '2026-09-07T14:00:00Z',
    updatedAt: '2026-09-08T10:15:00Z',
  },
];

export const INITIAL_COMPETITORS: CompetitorSnapshot[] = [
  {
    id: 'comp-001',
    workspaceId: 'ws-arthurs',
    websiteId: 'site-arthurs',
    competitorDomain: 'growthdigitalai.com',
    competitorName: 'Growth Digital AI',
    researchDate: '2026-09-05',
    sharedTopics: [
      'AI Marketing Automation',
      'Technical SEO Auditing',
      'Local Citation Management',
      'Content Generation at Scale',
    ],
    contentGaps: [
      {
        topic: 'AI Phone Receptionist & Voice Agents for Local Practices',
        competitorUrl: 'https://growthdigitalai.com/services/ai-voice-reception',
        opportunityExplanation: 'Competitor ranks in top 3 for medical receptionist AI; Arthur’s Creatives has proven case studies in this niche but lacks a dedicated high-intent landing page.',
        estimatedValue: 'High commercial intent ($6.50 CPC equivalent)',
      },
      {
        topic: 'Automated Local SEO Citation Consistency Verification',
        competitorUrl: 'https://growthdigitalai.com/solutions/local-citations',
        opportunityExplanation: 'Competitor highlights NAP discrepancy checks. We can showcase our LOVE Brain automated directory audit.',
        estimatedValue: 'Medium intent, high retention feature',
      },
    ],
    observedStrengths: [
      'Strong interactive ROI calculator for agency client pitch meetings.',
      'Detailed API documentation for custom CRM integrations.',
    ],
    observedWeaknesses: [
      'Audit reports are static PDFs without interactive task management.',
      'Content generation tool lacks factual claim verification flags.',
    ],
    publicCTAs: [
      'Book a 15-Minute AI Strategy Demo',
      'Calculate Your Agency Labor Savings',
    ],
    topRankingPages: [
      {
        title: 'How AI Agents Scale Client Workflows Without Hiring',
        url: 'https://growthdigitalai.com/blog/scale-workflows-ai-agents',
        primaryKeyword: 'ai workforce agency',
      },
    ],
  },
];

export const INITIAL_BUSINESS_PROFILE: BusinessProfile = {
  id: 'profile-arthurs',
  websiteId: 'site-arthurs',
  businessName: 'Arthur’s Creatives',
  category: 'Marketing Agency / AI Automation Services',
  address: '1104 S Congress Ave, Suite 300, Austin, TX 78704',
  serviceArea: 'Austin Metro & Nationwide Digital Services',
  phone: '+1 (512) 555-0198',
  websiteUrl: 'https://arthurscreatives.com',
  hours: 'Monday – Friday: 8:30 AM – 6:00 PM CST',
  services: [
    'AI-Powered SEO Audits',
    'Custom Digital Workforce Development',
    'AI Phone Receptionists',
    'Autonomous Customer Service Chatbots',
    'Local SEO & Citation Consistency',
  ],
  businessDescription: 'Arthur’s Creatives is a premier digital automation and growth agency. We build, train, and deploy intelligent AI agents and high-performance SEO architectures that turn organic search visitors into loyal customers.',
  socialProfiles: [
    { platform: 'LinkedIn', url: 'https://linkedin.com/company/arthurs-creatives' },
    { platform: 'X / Twitter', url: 'https://x.com/arthurscreatives' },
    { platform: 'YouTube', url: 'https://youtube.com/@arthurscreatives' },
  ],
  gbpConnected: true,
  gbpSyncStatus: 'Verified',
  directoryListings: [
    {
      directory: 'Google Business Profile',
      status: 'Consistent',
      listedName: 'Arthur’s Creatives',
      listedAddress: '1104 S Congress Ave, Suite 300, Austin, TX 78704',
      listedPhone: '+1 (512) 555-0198',
      lastChecked: '2026-09-08',
    },
    {
      directory: 'Apple Maps',
      status: 'Consistent',
      listedName: 'Arthur’s Creatives',
      listedAddress: '1104 S Congress Ave, Suite 300, Austin, TX 78704',
      listedPhone: '+1 (512) 555-0198',
      lastChecked: '2026-09-08',
    },
    {
      directory: 'Bing Places for Business',
      status: 'Consistent',
      listedName: 'Arthur’s Creatives',
      listedAddress: '1104 S Congress Ave, Suite 300, Austin, TX 78704',
      listedPhone: '+1 (512) 555-0198',
      lastChecked: '2026-09-08',
    },
    {
      directory: 'Yelp Business',
      status: 'Mismatch',
      listedName: 'Arthurs Creative Marketing LLC',
      listedAddress: '1104 S Congress Ave #300, Austin, TX 78704',
      listedPhone: '+1 (512) 555-0144',
      lastChecked: '2026-09-08',
    },
  ],
};

export const INITIAL_LEADS: LeadItem[] = [
  {
    id: 'lead-001',
    workspaceId: 'ws-arthurs',
    websiteId: 'site-arthurs',
    name: 'Samantha Hayes',
    company: 'BlueRidge Dental Associates',
    website: 'https://blueridgedental.example.com',
    email: 'samantha@blueridgedental.example.com',
    phone: '(512) 890-2134',
    requestedService: 'Local SEO Audit & AI Phone Receptionist',
    source: 'Website Audit Request Form',
    notes: 'Requested urgent audit because local ranking dropped for "emergency dental Austin".',
    assignedOwner: 'Arthur Vance',
    followUpDate: '2026-09-12',
    status: 'Audit Sent',
    createdAt: '2026-09-08T18:40:00Z',
  },
  {
    id: 'lead-002',
    workspaceId: 'ws-arthurs',
    websiteId: 'site-arthurs',
    name: 'Carlos Mendez',
    company: 'Summit Solar Solutions',
    website: 'https://summitsolar.example.com',
    email: 'carlos@summitsolar.example.com',
    phone: '(210) 441-9921',
    requestedService: 'Enterprise SEO Retainer + Content Engine',
    source: 'Referral from Marcus Vance',
    notes: 'Wants to expand beyond San Antonio into Dallas and Houston markets.',
    assignedOwner: 'Arthur Vance',
    followUpDate: '2026-09-15',
    status: 'New',
    createdAt: '2026-09-09T09:20:00Z',
  },
];

export const INITIAL_REPORTS: ReportItem[] = [
  {
    id: 'rep-001',
    workspaceId: 'ws-arthurs',
    websiteId: 'site-arthurs',
    title: 'Monthly Organic Growth & Technical Audit Report (August 2026)',
    reportingPeriod: 'Aug 1, 2026 – Aug 31, 2026',
    generatedAt: '2026-09-01T08:00:00Z',
    isScheduled: true,
    frequency: 'Monthly',
    clientViewable: true,
    executiveSummary: 'Overall organic search health improved significantly following the technical cleanup of canonical tags and image compressions. AI SEO Love audit score increased from 76 to 84. Total organic clicks grew by +18.4% with average keyword position moving from 16.2 to 12.8.',
    dataSources: [
      'Google Search Console (Connected)',
      'Google Analytics 4 (Connected)',
      'AI SEO Love Technical Crawler Run #001',
    ],
    auditScoreChange: {
      previous: 76,
      current: 84,
    },
    completedTasksCount: 14,
    outstandingIssuesCount: 6,
    contentPiecesProduced: 3,
    searchPerformanceSnapshot: {
      totalClicks: 4210,
      totalImpressions: 98400,
      avgCTR: 4.28,
      avgPosition: 12.8,
    },
    keyRecommendations: [
      'Deploy missing canonical tag on /services/ai-seo-growth immediately.',
      'Publish drafted guide targeting "ai seo platform for agencies" to capture surging commercial queries.',
      'Fix Yelp directory phone number mismatch to reinforce local Austin NAP consistency.',
    ],
    deliveryStatus: 'Ready',
  },
];

export const INITIAL_INTEGRATIONS: IntegrationStatus[] = [
  {
    id: 'int-gsc',
    name: 'Google Search Console',
    category: 'Search & Analytics',
    status: 'Connected',
    lastSync: '2026-09-10T11:45:00Z',
    description: 'Retrieves actual verified impressions, clicks, CTR, and average query positions directly from Google.',
    supportedFeatures: ['Query rankings', 'Page impressions', 'Crawl indexing coverage', 'Sitemap verification'],
    configuredAccount: 'arthurscreatives@gmail.com (Sc-domain: arthurscreatives.com)',
  },
  {
    id: 'int-ga4',
    name: 'Google Analytics 4',
    category: 'Search & Analytics',
    status: 'Connected',
    lastSync: '2026-09-10T12:00:00Z',
    description: 'Measures organic user engagement, conversion funnels, bounce rates, and session durations.',
    supportedFeatures: ['Organic traffic trends', 'Goal conversions', 'Engagement rate', 'Device split'],
    configuredAccount: 'GA4 Property ID: 394820194',
  },
  {
    id: 'int-gemini',
    name: 'Gemini AI Model Provider',
    category: 'AI & Content',
    status: 'Connected',
    lastSync: '2026-09-10T14:15:00Z',
    description: 'Powers LOVE Brain and the 5 specialized AI workers for grounded reasoning, briefs, and fixes.',
    supportedFeatures: ['LOVE Brain Conversational Assistant', 'Technical Issue Analysis', 'Content Brief Generation', 'Competitor Gap Extraction'],
    configuredAccount: 'Server-Side Configured (gemini-3.8-flash)',
  },
  {
    id: 'int-dataforseo',
    name: 'DataForSEO Provider',
    category: 'Data Providers',
    status: 'Connected',
    lastSync: '2026-09-08T04:00:00Z',
    description: 'Supplies real-time SERP data, keyword volumes, difficulty indices, and cost-per-click estimates.',
    supportedFeatures: ['Monthly Search Volumes', 'SERP Competition Scores', 'CPC Estimates', 'Keyword Clusters'],
    configuredAccount: 'Active Live API Tier',
  },
  {
    id: 'int-tavily',
    name: 'Tavily Web Research',
    category: 'Data Providers',
    status: 'Connected',
    lastSync: '2026-09-07T18:00:00Z',
    description: 'Crawls public web sources to supply evidence-based competitor research snapshots.',
    supportedFeatures: ['Competitor page topic analysis', 'Public CTA tracking', 'Citation sources'],
    configuredAccount: 'Configured & Ready',
  },
  {
    id: 'int-semrush',
    name: 'Semrush Enterprise API',
    category: 'Data Providers',
    status: 'Not Connected',
    description: 'Connect Semrush account to pull proprietary backlink metrics and domain authority scores.',
    supportedFeatures: ['Backlink audits', 'Referring domain health', 'Historical domain rank'],
  },
  {
    id: 'int-stripe',
    name: 'Stripe Billing & Subscriptions',
    category: 'Business & CMS',
    status: 'Connected',
    lastSync: '2026-09-10T09:00:00Z',
    description: 'Manages workspace subscriptions, usage credits, invoice generation, and seat expansion.',
    supportedFeatures: ['Credit balance management', 'Automated recurring billing', 'Invoice receipts'],
    configuredAccount: 'Arthur’s Creatives Live Merchant Account',
  },
  {
    id: 'int-calendly',
    name: 'Calendly Booking',
    category: 'Business & CMS',
    status: 'Connected',
    lastSync: '2026-09-09T10:00:00Z',
    description: 'Embeds consultation booking links directly into audit reports and lead follow-up emails.',
    supportedFeatures: ['Direct client consultation scheduling', 'Audit presentation booking'],
    configuredAccount: 'calendly.com/arthurscreatives/seo-strategy-session',
  },
  {
    id: 'int-cms',
    name: 'CMS Publishing (WordPress / Webflow / Next.js)',
    category: 'Business & CMS',
    status: 'Not Connected',
    description: 'Enables explicit 1-click publishing of approved content items with rollback preservation.',
    supportedFeatures: ['Draft synchronization', 'Revision rollback preservation', 'Meta tag auto-injection'],
  },
  {
    id: 'int-email',
    name: 'Resend / SMTP Notification Provider',
    category: 'Communication',
    status: 'Connected',
    lastSync: '2026-09-10T08:30:00Z',
    description: 'Delivers scheduled white-label audit reports and critical technical alerts to team members.',
    supportedFeatures: ['Scheduled PDF report dispatch', 'Critical error alerts', 'Client portal invitations'],
    configuredAccount: 'reports@arthurscreatives.com',
  },
];

export const INITIAL_WORKER_ACTIVITIES: WorkerActivity[] = [
  {
    id: 'act-001',
    workerName: 'Technical SEO Worker',
    taskDescription: 'Analyzed crawl results for 24 pages on arthurscreatives.com. Identified missing canonical tag on /services/ai-seo-growth.',
    status: 'completed',
    startedAt: '2026-09-08T15:30:45Z',
    completedAt: '2026-09-08T15:31:02Z',
    sourceDataUsed: 'Audit Run #001 HTML DOM snapshots and HTTP headers.',
    outputSummary: 'Generated prioritized issue #issue-001 with exact `<head>` verification snippet.',
  },
  {
    id: 'act-002',
    workerName: 'Keyword Research Worker',
    taskDescription: 'Extracted high-intent keyword cluster around "ai digital workforce for business" and mapped to /services/digital-workforce.',
    status: 'completed',
    startedAt: '2026-09-08T16:10:00Z',
    completedAt: '2026-09-08T16:10:24Z',
    sourceDataUsed: 'DataForSEO SERP data & intent categorization engine.',
    outputSummary: 'Mapped 3 target keywords with combined search volume of 4,880.',
  },
  {
    id: 'act-003',
    workerName: 'Content Worker',
    taskDescription: 'Drafted 1,800-word comprehensive guide on agency AI SEO audits with factual review flags.',
    status: 'completed',
    startedAt: '2026-09-08T16:40:00Z',
    completedAt: '2026-09-08T16:41:15Z',
    sourceDataUsed: 'Active website business profile & authorized agency case studies.',
    outputSummary: 'Created ContentItem #cnt-001 currently in Review status with 2 factual verification notes.',
  },
  {
    id: 'act-004',
    workerName: 'Competitor Research Worker',
    taskDescription: 'Compared public landing pages of growthdigitalai.com against arthurscreatives.com service offerings.',
    status: 'completed',
    startedAt: '2026-09-09T08:00:00Z',
    completedAt: '2026-09-09T08:01:20Z',
    sourceDataUsed: 'Public heading structure, meta tags, and service page text.',
    outputSummary: 'Identified major content gap: "AI Phone Receptionist & Voice Agents for Local Practices".',
  },
  {
    id: 'act-005',
    workerName: 'Local SEO Worker',
    taskDescription: 'Ran NAP consistency check across Google Business Profile, Apple Maps, Bing Places, and Yelp.',
    status: 'completed',
    startedAt: '2026-09-09T11:00:00Z',
    completedAt: '2026-09-09T11:00:45Z',
    sourceDataUsed: 'Business profile address and directory public listings.',
    outputSummary: 'Detected phone number mismatch (+1 512-555-0144) on Yelp listing.',
  },
];

export const INITIAL_AI_MESSAGES: AIMessage[] = [
  {
    id: 'msg-001',
    role: 'assistant',
    content: `Welcome to **LOVE Brain**! I am your central AI SEO assistant for **Arthur’s Creatives**. 

I am actively connected to your workspace data for **arthurscreatives.com**, including your latest website audit (Score: 84/100), 5 tracked keywords, active content briefs, and directory listings.

Here is what I observe in your project right now:
- **Observed Fact:** You have 1 Critical technical issue: missing canonical tag on \`/services/ai-seo-growth\`.
- **Observed Fact:** 2 high-intent service pages lack meta descriptions, causing search engines to display arbitrary page snippets.
- **Observed Fact:** A phone number discrepancy exists on your Yelp business listing.

How would you like to proceed today? You can choose a quick action below or ask me anything!`,
    timestamp: '2026-09-09T12:00:00Z',
    sourceReferences: [
      { type: 'audit_finding', label: 'Audit Run #001', detail: 'Score 84/100, completed 2026-09-08' },
      { type: 'url', label: 'Affected URL', detail: 'https://arthurscreatives.com/services/ai-seo-growth' },
    ],
    observedFacts: [
      'Missing canonical tag on https://arthurscreatives.com/services/ai-seo-growth',
      'Yelp phone number listed as +1 (512) 555-0144 instead of +1 (512) 555-0198',
    ],
    hypotheses: [
      'Fixing the canonical tag will protect ranking authority against parameter duplicates.',
      'Adding dedicated meta descriptions typically lifts CTR by 8-15% on high-intent terms.',
    ],
    suggestedActions: [
      {
        type: 'create_task',
        label: 'Fix Canonical Tag on /services/ai-seo-growth',
        payload: { issueId: 'issue-001' },
      },
      {
        type: 'create_brief',
        label: 'Create Brief for "ai phone receptionist for clinics"',
        payload: { keywordId: 'kw-004' },
      },
      {
        type: 'run_audit',
        label: 'Run Fresh Audit on Competitor or New URL',
        payload: {},
      },
    ],
  },
];
